### ISSUE TITLE
[Bug]: <Secret Stardust Potion image not updating when using stored exp to level past milestone>

### ISSUE THREAD

**Issue by Felddagryph** [MelvorIdle/melvoridle.github.io#1687]
### Describe the bug

Secret Stardust potion still shows rank 1 image in the list of skill potions at mastery 30 when using stored mastery pool exp to level it.  Seems to be fine otherwise, shows rank 2 images in the create window.

### Screenshots

![image](https://user-images.githubusercontent.com/77302038/141675274-e33435ab-0400-4497-b0ed-389d6a9fef0d.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1286

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed in v1.0.2.
