### ISSUE TITLE
[Bug]: New astrology icons not updated in the milestones list

### ISSUE THREAD

**Issue by nekoyoubi** [MelvorIdle/melvoridle.github.io#2124]
### Describe the bug

The newly released (and beautiful) astrology icons do not appear to be in the skill's milestone roadmap.

![](https://i.imgur.com/SeCRMKL.png)

### Reproduction Steps

1. Navigate to the Astrology skill
2. See the pretty new icons on the main window
3. Click the ![](https://i.imgur.com/rcBSC7U.png)
4. See the old (reads: "charming") big dipper icons

### Expected behaviour

Consistent imagery  throughout the Astrology skill.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1523

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now hotfixed :)
