### ISSUE TITLE
[Bug]: Astrology symbols not on the Milestones breakdown

### ISSUE THREAD

**Issue by tea-sheep** [MelvorIdle/melvoridle.github.io#2133]
### Describe the bug

When you click on the "View Milestones for this skill" button, the old astrology art appears

### Reproduction Steps

Click "View Milestones for this skill" in astrology skill

### Expected behaviour

New art appears

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1523

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This has now been hotfixed :)
