### ISSUE TITLE
[Bug]: Thieving last milestone not working (triple unique drop)

### ISSUE THREAD

**Issue by esso23** [MelvorIdle/melvoridle.github.io#2303]
### Describe the bug

Noticed this on Princess after one of the recent updates. I got like 300 Jadestones in about 20 hours of thieving the princess with 88.18% success rate. I'm getting considerably less Jadestones than before.
I tried removing the milestone and my unique drop chance was:
0.009%
After unlocking the milestone it was:
0.010%

The difference was probably caused only by 100 thieving skill difference.

### Screenshots

![Screenshot 2022-03-06 22 49 17](https://user-images.githubusercontent.com/5548662/156943687-fc342fc4-b717-465d-b04c-cab74c519b79.png)
![Screenshot 2022-03-06 22 49 27](https://user-images.githubusercontent.com/5548662/156943690-ace8e87c-1e6f-48b9-a3e2-8bce26cc9355.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1829

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
The 95% mastery pool bonus applies to "Unique Area" drops, meaning the items that drop only from a specific thieving area. Jadestones are a "NPC unique" drop, so the bonus does not apply.
