### ISSUE TITLE
[Bug]: Wrong milestone smithing

### ISSUE THREAD

**Issue by ALittleOctopus** [MelvorIdle/melvoridle.github.io#2543]
### Describe the bug

The milestone of smithing have an error. Level 12 show iron shield (image and text) but this is incorrect. Level 12 is bronze shield.

### Screenshots

![lvl12](https://user-images.githubusercontent.com/109852803/180601029-9c99eacf-f6b4-48fa-ac41-b548f1f4754a.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
