### ISSUE TITLE
[Bug]: <All icons are gone EPIC>

### ISSUE THREAD

**Issue by Sfiry** [MelvorIdle/melvoridle.github.io#3917]
### Describe the bug

All game icons are gone

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57869970/ef1ca528-beeb-49e1-bc9e-78602fbb6608)

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57869970/0962334c-bcf9-402a-898c-e046214020a0)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8274

### Are you using any mods?

No

**Comment by valrorapa** [comment]
I solved it by verifying the game files
