### ISSUE TITLE
[Bug]: Epic Link Status Missing

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3920]
### Describe the bug

If the game is launched through Epic, the is an icon showing that the account is linked to Epic Games. However, this does not appear on other platforms.

### Reproduction Steps

1. Launch game on Epic
2. See the green check for Epic Games
3. Launch the game on Mobile or Website
4. See Epic Games missing

### Expected behaviour

There should be a green check if the account is linked to Epic Games when using other platforms.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/684977ae-3ddc-4415-b539-c164e2306e1a)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [x] Throne of the Herald
- [x] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8282

### Are you using any mods?

No
