### ISSUE TITLE
Epic full version not carrying over to mobile

### ISSUE THREAD

**Issue by diZesus** [MelvorIdle/melvoridle.github.io#3942]
### Describe the bug

As title says, I logged in with full version account from epic to mobile free/demo version. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

No

**Comment by Colonelc8** [comment]
I have same issue

**Comment by MelvorIdle** [comment]
**Demo on (Website, Mobile) OR Playing Cross platform:**
Launch the game through Epic. Upon reaching the character select, look in the top left corner for 'Epic Games'. If there is a ✅, try checking the other platform again (you will need to refresh/relaunch the game). If you do not see 'Epic Games' in the top left and you have a character that you would like to save, make a Melvor Cloud account and log into it first. A Melvor Cloud account is required for playing cross platform. This process will remove your local saves (if this is a problem, check the above comment).

If there is an ❌, Navigate to (Windows: `%LocalAppData%`, Mac: Open Finder and Command+Shift+G: `~/Library/Application Support`) and delete the Melvor Idle folder. This will log you out of your Melvor Idle and Epic Accounts and remove your local save data (cloud save data should be fine). After doing so, launch the game again.

When prompted to sign into Epic, **you need to make sure you are using the same account that is logged into the Epic Launcher**. If you sign into a different Epic account, you will need to restart this process.
