### ISSUE TITLE
[Bug]: Error importing Epic save to Android Beta

### ISSUE THREAD

**Issue by Shukillo** [MelvorIdle/melvoridle.github.io#3956]
### Describe the bug

I have saved my Epic Games save file to the cloud, to keep playing on my Android device. I have been doing this since I have the game, but now I receive this error:

createIncreaseHealthBtns@https://android.melvoridle.com/assets/js/built/township.js?8284:452:7
loadTownshipUI@https://android.melvoridle.com/assets/js/built/township.js?8284:449:505
postStatLoad@https://android.melvoridle.com/assets/js/built/township.js?8284:273:43
onLoad@https://android.melvoridle.com/assets/js/built/game.js?8284:197:361
updateWindow/<@https://android.melvoridle.com/assets/js/built/main.js?8284:12:189
__awaiter</<@https://android.melvoridle.com/assets/js/built/language.js?8284:5:58
__awaiter<@https://android.melvoridle.com/assets/js/built/language.js?8284:2:8
updateWindow@https://android.melvoridle.com/assets/js/built/main.js?8284:6:672
onSaveDataLoad/<@https://android.melvoridle.com/assets/js/built/main.js?8284:80:81
__awaiter</<@https://android.melvoridle.com/assets/js/built/language.js?8284:5:58
__awaiter<@https://android.melvoridle.com/assets/js/built/language.js?8284:2:8
onSaveDataLoad@https://android.melvoridle.com/assets/js/built/main.js?8284:80:34
loadSaveFromString/<@https://android.melvoridle.com/assets/js/built/save.js?8284:138:1
fulfilled@https://android.melvoridle.com/assets/js/built/language.js?8284:2:98

### Reproduction Steps

Login to Epic Games game
Load local game
Save the game to the cloud
Login in Android device
Try to load the cloud save file
The error is displayed (in Spanish)

![Imagen de WhatsApp 2023-12-28 a las 22 57 36_6ece1516](https://github.com/MelvorIdle/melvoridle.github.io/assets/10891231/462f292e-12b8-4343-964a-95aa4d1b2653)

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/PaNWygur

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

No

**Comment by Shukillo** [comment]
Update: The following day, it just worked. I have the feeling that the Android version wasn't detecting I own the full game from Epic Games...
