### ISSUE TITLE
[Bug]: Purchase validation causes Epic games timeout ban

### ISSUE THREAD

**Issue by Blacklotus45** [MelvorIdle/melvoridle.github.io#3957]
### Describe the bug

I mostly play by browser and mobile app. Login couple of times today like 7-8 times. This somehow caused API spam(?) to Epic games services and give me a undefined amount of timeout from all servers including bug report service(shame on you epic). On Melvor side I can't access to my expansions and may corrupt by save but I don't want to gamble. This is pretty bad when a error causes both systems to deny access including and not limited to Unreal Engine I use(thank god they also distribute offline edition)

### Reproduction Steps

You can't unless you know a way to trigger this with developer sdk or other methods.

### Expected behaviour

Melvor not causing a API saturation for Epic services.

Also Melvor should keep which accounts have expansions on it's own infrastructure after validation for first time. This way game can be more resilient to service outage of any third parties. May even decrease operational costs.

Clients used; Brave Browser(Chrome) and Android Beta, roughly a week ago Epic Games

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/22615437/d044397b-a2a6-4359-a5b1-b9a7997ebd8f)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/22615437/c96d6750-514c-4231-8080-7d6950a9d065)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/22615437/594585c0-6a79-4760-9950-167980cc14ba)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/22615437/4e22d4af-d99c-420d-91e8-2a47463fbc64)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

n/a

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I'm not sure why this would be occuring. Melvor Idle caches your purchase validations for 48 hours, so you're only pinging the Epic servers once every two days.

Is this issue still ocurring for you now? I know Epic Games have had many issues during their free promotion with login servers and whatnot going down.
