### ISSUE TITLE
[Bug]: Game not wanting to launch (Epic games launcher)

### ISSUE THREAD

**Issue by xcidip** [MelvorIdle/melvoridle.github.io#3967]
### Describe the bug

when opening the game it doesn't even show a window, it just closes right after the icon in the dock shows

### Reproduction Steps

1. On Macbook with a touchbar click on new tab on it
2. chromium windows opens with google.com and nothing else
3. can't launch the game after quitting the game trying to restart it back normal

### Expected behaviour

the should launch normally instead it closes immediately

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

1.0.0-11-osx-arm64-sdk (cant check in-game)

### Are you using any mods?

No
