### ISSUE TITLE
[Bug]: Infinite Loop On Epic Game Launch

### ISSUE THREAD

**Issue by ALLDiiie** [MelvorIdle/melvoridle.github.io#4042]
### Describe the bug

The game simply runs in a loop, changing the message between "You are about to be redirected" and "tentaive de connexion". The game fails to launch.

### Screenshots

![image (1)](https://github.com/MelvorIdle/melvoridle.github.io/assets/87877238/5d369082-1de0-4fc5-890d-d3cd54d7c3f5)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

cant see it

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I'm currently investigating this issue. I hope to have a fix out ASAP. I have a suspicion as to what causes it, fingers crossed it is what I think.

**Comment by MelvorIdle** [comment]
A hotfix has been pushed that will allow you to gain access to the game.
