### ISSUE TITLE
Login via Epic Games failing again

### ISSUE THREAD

**Issue by mbushman789** [MelvorIdle/melvoridle.github.io#4189]
### Describe the bug

Game does not seem to be recognizing login / purchase confirmation from Epic Games launcher. I have logged in and out several times over this morning - then it failed.

### Screenshots

![Screenshot 2024-04-10 104638](https://github.com/MelvorIdle/melvoridle.github.io/assets/159959519/290aa632-9e31-4d69-8953-6392af534d4f)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

1.0.0-14-x64-sdk

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Hello, thanks for the report. It looks like the issue was picked up by PlayFab and has now been resolved: https://status.playfab.com/
