### ISSUE TITLE
[Bug]: Runecrafting 25% Mastery Milestone not applied

### ISSUE THREAD

**Issue by SamCarraro** [MelvorIdle/melvoridle.github.io#4464]
### Describe the bug

The Runecrafting 25% Mastery Milestone (+150% EXP for Runecrafting Runes) is not applied. 

### Reproduction Steps

Go to Runecrafting
Reach 25% Runecrafting Milestone
Go to Air Rune
Check EXP still 10EXP

### Expected behaviour

Expected behaviour would be 10EXP + 150% of 10EXP -> 25EXP

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

11517

### Are you using any mods?

No

**Comment by Ayarez** [comment]
Base XP of Air Rune is 4 xp, 4+150% would be 10

**Comment by SamCarraro** [comment]
You are right then the description of the EXP modifier is wrong.
