### ISSUE TITLE
[Bug]: Abyssal level 60 modal has empty milestones section

### ISSUE THREAD

**Issue by SolidKalium** [MelvorIdle/melvoridle.github.io#4518]
### Describe the bug

When reaching the maximum level for an Abyssal skill, the popup has a section label for milestones that appears even when there are no milestones.

Note: This is difficult to reproduce. The game was no more than a couple days behind the most recent version on July 9, nine days ago, when I took the screen shot.

### Reproduction Steps

1. Reach level 60 in an Abyssal skill
2. Look at the modal
3. See a header with no content below it

### Expected behaviour

Either:
1) There is a milestone shown, such as "You can complete the Skill Tree", or
2) Neither a milestone nor the milestone header is shown

### Screenshots

![2024-07-09](https://github.com/user-attachments/assets/d8047532-0d4b-4e1f-9381-1d9870d9a32c)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

No
